name: test
on:
  push:
    branches:
    - main
  workflow_dispatch:
  pull_request:
    paths:
    - src/**
    - pyproject.toml
    - tests/**
    - "*_requirements.txt"
    - .github/workflows/test.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install Hatch
      uses: pypa/hatch@install
    - run: hatch run lint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        # - macos-latest
        python:
        - 3.8
        - 3.9
        - '3.10'
        - 3.11
        - 3.12
        - 3.13
    steps:
    - uses: actions/checkout@v4
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: test
      run: hatch run test.py${{ matrix.python }}:test
